// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAre7nCkGruqAJIipAP-wNKWQ6KNkixJ0w',
    appId: '1:519982720125:web:306f36cc21a505d6443d14',
    messagingSenderId: '519982720125',
    projectId: 'youmr-dev',
    authDomain: 'youmr-dev.firebaseapp.com',
    storageBucket: 'youmr-dev.firebasestorage.app',
    measurementId: 'G-K6PBSYM4D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sqejN7mxTFaCIQ_mS2h4ms_d-1zPLvg',
    appId: '1:519982720125:android:fb7fe8652fb70620443d14',
    messagingSenderId: '519982720125',
    projectId: 'youmr-dev',
    storageBucket: 'youmr-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7pQ0DMwAL4kXrefp7n5YBYOZgehFXWo',
    appId: '1:519982720125:ios:8e505bcbdf19c0ca443d14',
    messagingSenderId: '519982720125',
    projectId: 'youmr-dev',
    storageBucket: 'youmr-dev.firebasestorage.app',
    iosBundleId: 'com.youmr.youmrV2',
  );
}
