// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0wOtl35EvWuPo1jJV_MfKIG8p-DVcqM',
    appId: '1:756931774464:web:7925919cc4cf85b0a4f0e5',
    messagingSenderId: '756931774464',
    projectId: 'youmr-v2',
    authDomain: 'youmr-v2.firebaseapp.com',
    storageBucket: 'youmr-v2.firebasestorage.app',
    measurementId: 'G-BT8XSSB8YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDepXTG53Am5CoLcBY2CnahH97A3MUwuCU',
    appId: '1:756931774464:android:7d7b1958143f66eaa4f0e5',
    messagingSenderId: '756931774464',
    projectId: 'youmr-v2',
    storageBucket: 'youmr-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-nI7gljCxvxyCfoVClce6fS4D7KinnP8',
    appId: '1:756931774464:ios:8be8e4df15799a89a4f0e5',
    messagingSenderId: '756931774464',
    projectId: 'youmr-v2',
    storageBucket: 'youmr-v2.firebasestorage.app',
    iosBundleId: 'com.youmr.youmrV2',
  );
}
